import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

export default function ProductLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
